### ISSUE TITLE
Allow for alternate sound_definitions.json file format

### ISSUE THREAD

**Issue by AdamRaichu** [Blockception/Minecraft-bedrock-json-schemas#119]
Currently, the schema for `rp/sounds/sound_definitions.json` requires using the `sound_definitions` object. However, omitting `format_version` and simply objects (example below) also works.

```JSON
{
  "guns.sniper.fire": {
    "category": "neutral",
    "sounds": [
      "sounds/sniper_sound"
    ]
  }
}
```

Perhaps prevent schema from showing errors by allowing this file format.

**Comment by DaanV2** [comment]
I know this is supported, because this is how Minecraft started with it, they want to move over to the format version. So that if there are heavy changes it properly formatted :)

For that I am closing this issue, as I believe that using a format version is the way forward
