### ISSUE TITLE
`minecraft:creative_category` component missing from item components

### ISSUE THREAD

**Issue by AdamRaichu** [Blockception/Minecraft-bedrock-json-schemas#125]
While the schema seems to exist for block definition files, and `description.category` seems to work, `components.minecraft:creative_category` does not appear in autocomplete.

**Comment by AdamRaichu** [comment]
Also, `description.register_to_creative_menu` seems to be missing and generates an error when using schema, even though it is used in [this Microsoft tutorial](https://learn.microsoft.com/en-us/minecraft/creator/documents/customblock).

**Comment by DaanV2** [comment]
Talked to MS, `description.category` Is the way to go, creative_category is going out the door

**Comment by AdamRaichu** [comment]
If `minecraft:creative_category` shouldn't be used, how is `itemGroup` supposed to be specified?

**Comment by DaanV2** [comment]
There is a field in description.category that you can use :)

**Comment by AdamRaichu** [comment]
The current item schemas expect a string. Could the schemas be updated to show an object? ([Docs](https://learn.microsoft.com/en-us/minecraft/creator/reference/content/itemreference/examples/itemdefinition) are unhelpful.)

**Comment by AdamRaichu** [comment]
![image](https://user-images.githubusercontent.com/91494019/196807564-95336c2a-154c-470e-b96d-dcbf99456be4.png)

Category actually only allows string...

**Comment by Xterionix** [comment]
Should be closed now I believe
