### ISSUE TITLE
Support for VSCode snippets scheme in examples

### ISSUE THREAD

**Issue by mitgobla** [Blockception/Minecraft-bedrock-json-schemas#126]
**Is your feature request related to a problem? Please describe.**
When inserting a snippet in VSCode, such as CTRL+SPACE in an <example>.animation_controller.json file for an animation controller, the example it pastes puts the cursor at the end of the file. It takes an additional action to then edit the name. Snippets from other languages use the VSCode placeholder syntax to allow you to tab through placeholder positions in the snippet making filling values far faster. 

It seems in some places the cursor does get moved to a useful position, however. For example, inserting the example animation controller state will put the cursor onto "default" on "initial_state".

**Describe the solution you'd like**
Support for placeholders inside of JSON examples so that pressing tab can be used to quickly fill values. See [https://code.visualstudio.com/docs/editor/userdefinedsnippets](https://code.visualstudio.com/docs/editor/userdefinedsnippets)

**Describe alternatives you've considered**
- Manually moving the cursor to fill in values. Just a small extra step that can be a bit tedious.

**Additional context**
- If this is supported, I will be more than happy to make a PR updating many of the example snippets to include placeholders
- This will come in useful for all JSON examples, such as filling in behavior component values, names of animations, entity identifiers, and so on...

How replacement would look:

From:

```json
{
    "format_version": "1.19.0",
    "animation_controllers": {
        "controller.animation.example": {
            "states": {
                "default": {
                    "transitions": [
                        {
                            "state_1": "query.is_baby"
                        }
                    ]
                },
                "state_1": {
                    "animations": [
                        "state_1"
                    ],
                    "transitions": [
                        {
                            "default": "query.all_animations_finished"
                        }
                    ]
                }
            }
        }
    }
}
```
  
 to
 
 ```json
 {
    "format_version": "1.19.0",
    "animation_controllers": {
        "controller.animation.${1:example}": {
            "initial_state": "${2:default}",
            "states": {
                "${2:default}": {
                    "animations": [
                        "$3"
                    ],
                    "transitions": [
                        "$0"
                    ]
                }
            }
        }
    }
}
```

`$0` is not the first location, but is the last.

**Comment by DaanV2** [comment]
Already discussed in #7 

It allowed to be added 😄
