### ISSUE TITLE
`uuid` in manifest schemas use "an" instead of "a" 

### ISSUE THREAD

**Issue by AdamRaichu** [Blockception/Minecraft-bedrock-json-schemas#127]
The schema description for `uuid` property, in `header.uuid`, `modules[].uuid`, and `dependencies.uuid` all have the following description on hover. 

```
An UUID V4

A valid uuid v4.
```

I believe "An UUID V4" should be "A UUID V4", and that "uuid" should be capitalized in the detailed description.

**Comment by DaanV2** [comment]
Checking the rules, but it's `a UUID` as acronym follow different rules :P
