### ISSUE TITLE
Issue with "blocks.json" expecting a string in format version should be number list. eg [1,1,0]

### ISSUE THREAD

**Issue by StealthyExpertX** [Blockception/Minecraft-bedrock-json-schemas#156]
**Describe the bug**
Found an issue with the blocks.json in the resource pack root directory, the "format_version" expects a string but in the blocks.json it takes a list of numbers as shown in my example below.

"blocks.json"

**To Reproduce**
1. Load blocks.json file from vanilla Minecraft Bedrock.
2. Click on the "format_version"
3. The pop-up will show that it expects a string and will highlight it in yellow.
4. You will see the error even though it should be using a list version number like a manifest.json files version def.

**Expected behavior**
Should be able to load the file without the error appearing.

**Screenshots**
![image](https://user-images.githubusercontent.com/17806994/219876766-3a49c3b2-96fc-4eed-b096-9367a993059c.png)

**Desktop:**
 - OS: WINDOWS 10
 - Browser VS STUDIOS CODE
 - Version Current as of 2/18/2023

**Additional context**
N/A

**Comment by DaanV2** [comment]
Fixed with #157 157
