### ISSUE TITLE
"agent.json" Behavior Issue with "events" key not existing.

### ISSUE THREAD

**Issue by StealthyExpertX** [Blockception/Minecraft-bedrock-json-schemas#158]
**Describe the bug**
The issue with the behavior "agent.json" found in vanilla Minecraft's if the "events" key doesn't exist but an empty "component_groups"

This means it will error out with the vanilla agent.json file.
[agent.zip](https://github.com/Blockception/Minecraft-bedrock-json-schemas/files/10775290/agent.zip)

**To Reproduce**

1. Load the agent.json behavior provided in this report.
2. You will notice that the whole file will error as invalid.
3. This is because the "events" key is actually optional in Minecraft.

**Expected behavior**
It should load as a valid file even with no "events" key present and the "events" key shouldn't be required in behaviors as a depenscy.

**Screenshots**
![image](https://user-images.githubusercontent.com/17806994/219901840-c8eda7a1-3b15-4da4-8c1d-bfc49cfdc357.png)

**Desktop:**
 - OS: WINDOWS 10
 - Browser VS Code
 - v5.0.7

**Additional context**
N/A

**Comment by StealthyExpertX** [comment]
I'm not able to figure out how to resolve this yet, maybe somebody else in the community would be able to contribute to fixing this.

**Comment by DaanV2** [comment]
Aah, if you have component_groups property, its expect that you have events

**Comment by StealthyExpertX** [comment]
So this is in Minecraft's behaviors my guess is the devs just wanted to not include the json keys?

**Comment by DaanV2** [comment]
Yeah
