### ISSUE TITLE
Add `"$schema"` property to compiled Schemas, to reflect that they have been built for draft-07.

### ISSUE THREAD

**Issue by SirLich** [Blockception/Minecraft-bedrock-json-schemas#17]
**Is your feature request related to a problem? Please describe.**
I would like to use these schemas with the validation library [python jsonschema](https://python-jsonschema.readthedocs.io/en/stable/). This library assumes latest draft, unless explicitly supplied. I need to manually add the `"$schema"` property into the schemas, before I can validate.

**Describe the solution you'd like**
``"$schema"`` can be included in the generated schemas, either by including in source schemas, or adding into compilation pipeline.

**Describe alternatives you've considered**
I will inject manually, after pulling git submodule.

**Additional context**
Its a dumb project, but src is here: https://github.com/Bedrock-OSS/bedrock-web-validator

**Comment by DaanV2** [comment]
Schemas should now include that value.
