### ISSUE TITLE
Remove Invalid Entity Behavior Component: move_towards_restriction

### ISSUE THREAD

**Issue by DrinkWater623** [Blockception/Minecraft-bedrock-json-schemas#179]
This is not a valid component:
[move_towards_restriction.json](https://github.com/Blockception/Minecraft-bedrock-json-schemas/blob/main/source/behavior/entities/format/behaviors/move_towards_restriction.json)

It is not on the MS-Learn site and it is not used in any vanilla mob.

I'd do it in the fork/pull request I am working on, but I do not know how to indicate file deletion.

**Comment by Xterionix** [comment]
Not invalid afaik
https://bedrock.dev/docs/1.16.0.0/1.16.100.56/Entities#minecraft:behavior.move_towards_restriction

**Comment by Xterionix** [comment]
I think this can be closed since it's not an invalid component
