### ISSUE TITLE
Fill in description fields for render_controlers

### ISSUE THREAD

**Issue by DaanV2** [Blockception/Minecraft-bedrock-json-schemas#18]
The render_controller description field needs updating.

[source\resource\animations\actor_animation.json](https://github.com/Blockception/Minecraft-bedrock-json-schemas/blob/main/source/resource/animations/actor_animation.json)

**Comment by Xterionix** [comment]
I'm assuming this is for the client entity? And not rp animation

**Comment by Xterionix** [comment]
Though I'm not seeing any empty description fields for the render controller

**Comment by Xterionix** [comment]
What's this about?

**Comment by DaanV2** [comment]
Think its already done
