### ISSUE TITLE
Issue with stacked_by_data

### ISSUE THREAD

**Issue by tryashtar** [Blockception/Minecraft-bedrock-json-schemas#183]
[This line](https://github.com/Blockception/Minecraft-bedrock-json-schemas/blob/f6b40b85f3ed9b9817811c256f5dccd7fb18be92/source/behavior/items/format/minecraft.item.json#L65) points `stacked_by_data` to `knockback_resistance` instead of `stacked_by_data`.

And [this file](https://github.com/Blockception/Minecraft-bedrock-json-schemas/blob/f6b40b85f3ed9b9817811c256f5dccd7fb18be92/source/behavior/items/format/components/stacked_by_data.json) seems to be about `on_use` instead of `stacked_by_data`.

I would make a PR for this, but I don't know what `stacked_by_data` does (the official docs, as always, are useless -- it's not even clear if so-called "aux" values are even possible to add to custom items). Anyway just a very minor note :)

**Comment by Xterionix** [comment]
Has been resolved as per my items PR so this can be closed
