### ISSUE TITLE
block json schema diverges from instructions

### ISSUE THREAD

**Issue by rendall** [Blockception/Minecraft-bedrock-json-schemas#193]
This page on the Microsoft "learn" site <https://learn.microsoft.com/en-us/minecraft/creator/reference/content/blockreference/examples/blockstatesandpermutations> has this code:

```JSON
{
  "format_version": "1.19.40",
  "minecraft:block": {
    "description": {
      "identifier": "custom:lamp_block",
      "state": {
        "custom:is_lit": [ true, false ]
      }
    },
    "permutations": {
      {
        "condition": "query.block_state('custom:is_lit') == true",
        "components": {
          "minecraft:light_emission": 15
        }
      },
      {
        "condition": "query.block_state('custom:is_lit') == false",
        "components": {
          "minecraft:light_emission": 0
        }
      }
    },
    "components": {
      "minecraft:friction": 0.6,
      "minecraft:map_color": "#00ff00" 
    }
  }
}
```

The Blockception Minecraft Bedrock Development JSON schema for this block file flags the "state" property as *Property state is not allowed.* The JSON schema should be brought into alignment with the official instructions.

**To Reproduce**
1. Go to <https://learn.microsoft.com/en-us/minecraft/creator/reference/content/blockreference/examples/blockstatesandpermutations>
2. Copy and paste the code *below* into a JSON file representing a custom block, e.g. behavior_packs\custom_behavior_pack\blocks\custom_block.json
3. NB: *The code example on the Microsoft learn site has another error aside from this issue. Replace the curly brackets with square brackets after `"permutations"`, e.g.
```JSON
{
  "format_version": "1.19.40",
  "minecraft:block": {
    "description": {
      "identifier": "custom:lamp_block",
      "state": {
        "custom:is_lit": [ true, false ]
      }
    },
    "permutations": [ 
      {
        "condition": "query.block_state('custom:is_lit') == true",
        "components": {
          "minecraft:light_emission": 15
        }
      },
      {
        "condition": "query.block_state('custom:is_lit') == false",
        "components": {
          "minecraft:light_emission": 0
        }
      }
     ],
    "components": {
      "minecraft:friction": 0.6,
      "minecraft:map_color": "#00ff00" 
    }
  }
}
```
4. After updating the `"permutations"` value to be an array, note the squiggly line under "state" with the warning "Property state is not allowed."

**Expected behavior**
The JSON schema should be consistent with the instructions.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - VS Code: v1.83.1

**Additional context**
I suppose it's possible that the instructions are incorrect and the schema is correct, but I don't see any reference to "state" or "states" in the [block schema](source/behavior/blocks/format/minecraft.block.json)

**Comment by rendall** [comment]
Additionally, according to <https://learn.microsoft.com/en-us/minecraft/creator/reference/content/blockreference/examples/blockdescription> the expected field would be `"states"` and not `"state"`, so that may be another error with the JSON example on that page?

**Comment by rendall** [comment]
Looking at the other issues, I see that this is a group effort, here.  I'll verify which it's supposed to be and then submit a PR when I have a chance.

**Comment by rendall** [comment]
I have verified that `"states"` (plural) is the correct field, but that `Holiday Creator Features` must be toggled ON.

Does this extension support experimental features?  If not, we can close this?

**Comment by DaanV2** [comment]
> I have verified that `"states"` (plural) is the correct field, but that `Holiday Creator Features` must be toggled ON.
> 
> Does this extension support experimental features?  If not, we can close this?

Ish, I don't maintain it as much as it has potential problem if I lead people in the wrong direction, however a little bit of support will go along way.

Do we can leave it open for now, if someone wants to pick it up, then great maybe I'll do it myself if I have time 😁

**Comment by DaanV2** [comment]
Recently changed it myself from properties to states

**Comment by rendall** [comment]
Hey awesome!

**Comment by rendall** [comment]
Let me know if I can help.  Testing or whatever.

**Comment by rendall** [comment]
I have verified that it is there and working in the extension!  Awesome.  

The format is documented as:

```JSON
"states": {
  "namespace:statename1": [ 1, 2, 3... ],
  "namespace:statename2": [true, false],
  "namespace:statename3": {"values":{"min":0,"max":3}}
  ...
}
```

but for me, if the state is anything other than `[true,false]` I cannot get it to actually load and be available in the game.

Anyway, feel free to close! 👍🏻

**Comment by DaanV2** [comment]
Thank you too!
