### ISSUE TITLE
Attribute components

### ISSUE THREAD

**Issue by tryashtar** [Blockception/Minecraft-bedrock-json-schemas#199]
There are nine attribute components:
* `minecraft:health`
* `minecraft:knockback_resistance`
* `minecraft:movement`
* `minecraft:underwater_movement`
* `minecraft:lava_movement`
* `minecraft:follow_range`
* `minecraft:attack_damage`
* `minecraft:luck`
* `minecraft:absorption`

They all have the same fields, all optional:
* `value`: a `range_number_type` (source/behavior/entities/format/types/range_number_type.json)
* `min`: a float
* `max`: a float

Currently, these schemas:
* Wants `health`, `follow_range`, and `attack_damage` to use integers instead of floats
* Only likes ranges for `value` in `movement`
* Only likes `max` in `health`, `movement`, and `follow_range`
* Doesn't like `min` anywhere
* Doesn't have `luck` or `absorption` at all

I'd be happy to fix this myself, but I don't have an environment to test my changes 🙂
If I could get some help with that, I'll gladly help with this and more!

**Comment by DaanV2** [comment]
In the schema, there is a test folder with files with correct and wrong examples, and I apply the relevant schemas against them.

That uses the vscode-settings.json to specify which schemas have to match which files, you can update that to use local version.

you can also add this to a json file and it should work:

```json
"$schema": "./some-file.json"
```
