### ISSUE TITLE
breathable weirdness

### ISSUE THREAD

**Issue by tryashtar** [Blockception/Minecraft-bedrock-json-schemas#201]
`breathable` will read from `totalSupply` and `suffocateTime` if `total_supply` and `suffocate_time` are not present, respectively. I'm not sure why, but like 3 vanilla entities do it that way.

**Comment by DaanV2** [comment]
It unfortunallity one of those things mojang themself have much more control over :/ they use a regex like parser. While I would have to define a both as a valid field, and to be able to exclude one or the other, if the other is present is a hell to do.

So I took the easiest way out and was to only support the spec. Which should be snake_case.

It is a bug, but I will not support to keep the schemas easy :)

**Comment by tryashtar** [comment]
That's fair. It's weird to see warnings in the vanilla pack, but then again the vanilla pack has some actual objectively wrong schema errors too, so 🙃
