### ISSUE TITLE
load_on_low_memory in sound_definitions.json is deprecated

### ISSUE THREAD

**Issue by DaanV2** [Blockception/Minecraft-bedrock-json-schemas#202]
**Is your feature request related to a problem? Please describe.**
load_on_low_memory in sound_definitions.json is deprecated

**Describe the solution you'd like**
Removing the field from the schema

see also https://github.com/Blockception/BC-Minecraft-Bedrock-Diagnoser/issues/151

**Comment by Xterionix** [comment]
Resolved as per #218 
Didn't realize I had committed that in the same pr
