### ISSUE TITLE
"minecraft:icon" component format has changed (1.20.60+)

### ISSUE THREAD

**Issue by Hatchibombotar** [Blockception/Minecraft-bedrock-json-schemas#221]
`minecraft:icon` has a different format in format versions 1.20.60+
It is now:
```json
"minecraft:icon": {
      "default": "custom_item"
}
```

**Comment by Hatchibombotar** [comment]
Sorry, this is the wrong syntax
Correct one below:
"minecraft:icon": {
      "textures": {
             "default": "custom_item"
      }
}

**Comment by CountedElkO** [comment]
"minecraft:icon": {
      "textures": {
             "default": "custom_item"
      }
}
This is still throwing an error for me.
I have "raw_platinum": {"textures": "path/to/png"} in my item_texture.json
No matter what format I use in the BP/items/custom_item.json for the icon it either doesn't work in-game or throws a red error that isn't an error.

**Comment by Xterionix** [comment]
@CountedElkO Are you using regolith?

**Comment by CountedElkO** [comment]
@Xterionix no, I do not know what that is.
I am using VSCode with the Blockception extension with little to no custimization of VSCode.

**Comment by Xterionix** [comment]
This isn't a schema related btw. Open an issue on this repo https://github.com/Blockception/BC-Minecraft-Bedrock-Diagnoser
