### ISSUE TITLE
Add the entity description spawn_category new attribute

### ISSUE THREAD

**Issue by mammerla** [Blockception/Minecraft-bedrock-json-schemas#223]
**Describe the bug**
In preview versions for 1.20.80, a new preview attribute was added to entity json. This is patterned from spawn_category's on Java.

```
  "minecraft:entity": {
    "description": {
      "identifier": "minecraft:llama_spit",
      "spawn_category": "misc",
```
I believe potential values for this are:

monster
creature
ambient
axolotls
underground_water_creature
water_creature
water_ambient
misc

**To Reproduce**
See preview JSON files, e.g.: https://github.com/Mojang/bedrock-samples/blob/preview/behavior_pack/entities/llama_spit.json

**Expected behavior**
This property is still in preview and not fully implemented. We'd recommend most creator content either leaves this empty or sets it to misc. Nevertheless, would be good to get into the schemas.

**Additional context**
I'd be happy to look to attempt a PR for this if you'd like.

**Comment by DaanV2** [comment]
Sounds good! If you need or anyone else to jump in let me know :)
