### ISSUE TITLE
Add block traits

### ISSUE THREAD

**Issue by mammerla** [Blockception/Minecraft-bedrock-json-schemas#224]
**Describe the bug**
Per the introduced ~about 5 months ago, add block trait schemas to blocks.json

**To Reproduce**
Per https://learn.microsoft.com/en-us/minecraft/creator/reference/content/blockreference/examples/blocktraits - I don't think there is traits-related info in block JSON schema

**Additional context**
Happy to take a crack at a PR, just posting this issue ahead of time for your review :)

**Comment by DaanV2** [comment]
Sounds good! If you need or anyone else to jump in let me know :)
