### ISSUE TITLE
Fix typo and allow douse_fire to be an object

### ISSUE THREAD

**Issue by Xterionix** [Blockception/Minecraft-bedrock-json-schemas#240]
![image](https://github.com/Blockception/Minecraft-bedrock-json-schemas/assets/72647213/ad26ce9f-0570-4ab6-8266-6b7e2cc41b5a)
From splash potion

**Comment by DaanV2** [comment]
By spec it should be a boolean value. If this is just in the vanilla files, It can still be an error as they are imperfect. I rather enforce it that its must be a boolean incase they fix it

**Comment by Xterionix** [comment]
Alr I'll undo this too
