### ISSUE TITLE
Allow teleport_owner to be an object

### ISSUE THREAD

**Issue by Xterionix** [Blockception/Minecraft-bedrock-json-schemas#247]
![image](https://github.com/Blockception/Minecraft-bedrock-json-schemas/assets/72647213/a3c05ffc-4d73-4ca4-8526-5ed902237956)

**Comment by DaanV2** [comment]
If this is done once in vanilla files, And it should be a boolean, then I rather say this is an error in vanilla files and enforce that it is an boolean

**Comment by Xterionix** [comment]
Alr I'll undo this
