### ISSUE TITLE
Replace `examples` with `defaultSnippets`

### ISSUE THREAD

**Issue by ink0rr** [Blockception/Minecraft-bedrock-json-schemas#276]
**Is your feature request related to a problem? Please describe.**
The `examples` while useful, is kinda annoying to use because they put your cursor at the end of the example body, which makes it hard to modify the values because you have to navigate your cursor manually back to the value that you want to edit. This can make the editing experience slower than creating an empty object.

**Describe the solution you'd like**
Replace the `examples` with `defaultSnippets`. Not every single one, but I think most of them will benefit more from using snippets. Snippets can also use [variables](https://code.visualstudio.com/docs/editor/userdefinedsnippets#_variables) which might be useful to set default values based on the name of the file that is currently being edited.
I can work on replacing the `examples` with `defaultSnippets` if allowed.

**Describe alternatives you've considered**
Remove all the `examples` altogether. Which works for me personally as I've done it locally, but I think providing snippets is a way better solution for everyone.

**Additional context**
Editing without snippets, I have to move my cursor a lot just to navigate to the parts that I want to edit.

https://github.com/Blockception/Minecraft-bedrock-json-schemas/assets/18375098/f1849ee7-c243-47c9-91fb-e8e5f451366b

Editing with snippets, I can just press tab to navigate between the parts that I want to edit. It also creates the animation controller name based on the current file name, which is pretty convenient.

https://github.com/Blockception/Minecraft-bedrock-json-schemas/assets/18375098/6dc6d04e-963e-4256-a9e1-8555d8522224

**Comment by DaanV2** [comment]
I don't mind adding default snippets, but it's something that only vscode added, so I don't want to remove examples

**Comment by Xterionix** [comment]
Wouldn't they overlap if they were both kept?

**Comment by ink0rr** [comment]
Having them both works too. 
I initially thought the examples would be useless if we have snippets, I didn't know that it's a vscode specific feature.
