### ISSUE TITLE
minecraft:icon component autocomplete error

### ISSUE THREAD

**Issue by Ctufte08** [Blockception/Minecraft-bedrock-json-schemas#277]
When using the autocomplete format for the minecraft:icon component on items it gives you the wrong format for the component.
Autocomplete format:
```json
"minecraft:icon": {
    "textures": {
        "default": "stick"
    }
}
```
That format does not work and just gives the item no texture.
This format that I found does work:
```json
"minecraft:icon": {
    "texture": "stick"
}
```

Minecraft Bedrock Version: 1.20.73
Extension Version: 7.0.42
File format version: 1.20.50

**Comment by Xterionix** [comment]
Blockception only supports the latest formats. The "incorrect one" actually works from 1.20.70+. You are recommended to update your files accordingly or ignore the schema error.

**Comment by Xterionix** [comment]
Thoughts? @DaanV2

**Comment by DaanV2** [comment]
Tested this in 1.20.81 and this worked for me:

```json
"minecraft:icon": {
    "textures": {
        "default": "stick"
    }
}
```

Anything else didn't work for me, or Minecraft threw errors. Im closing this for now as works as intentend

**Comment by DaanV2** [comment]
Found that the following also still works:

```json
"minecraft:icon": "stick",
```
