### ISSUE TITLE
Update geometry identifier to allow for : in it

### ISSUE THREAD

**Issue by Xterionix** [Blockception/Minecraft-bedrock-json-schemas#296]
Self explanatory

**Comment by DaanV2** [comment]
Sorry this isn;t really explanarty, I going to need either documentation link or examples 🤔

**Comment by Xterionix** [comment]
Basically allow for `geometry.namespace:name`

**Comment by Xterionix** [comment]
For context, the mctools site suggests naming geometries like that and the built in block geometries also use this format

**Comment by DaanV2** [comment]
Ugh, this is totally colliding with their inherits system....

**Comment by Xterionix** [comment]
I made a PR to the project repo that I think sufficiently works around that

**Comment by DaanV2** [comment]
Yeah, but also going to need to update the minecraft bedrock project, its splits the geo name on :

because in vanilla files you can find things like:

`geometry.zombie:geometry:humaniond`

**Comment by Xterionix** [comment]
The block geometry files don't exist in the resource pack though

**Comment by DaanV2** [comment]
This kinda needs to be coherent though, there shouldn't be special rules between different geo files :/

In best practise atleast

**Comment by Xterionix** [comment]
True
