### ISSUE TITLE
1.16.0 Geometry Format Version

### ISSUE THREAD

**Issue by JannisX11** [Blockception/Minecraft-bedrock-json-schemas#4]
**Describe the bug**
The 1.16.0 geometry format version is not recognized and is marked as invalid. The new format version is required for the new "binding" property on bones to work.

**To Reproduce**
1. Create a regular 1.12 geometry
2. Change the format version to "1.16.0"
3. Geometry file is marked as invalid

**Expected behavior**
The geometry file should be valid.

**Comment by DaanV2** [comment]
Apparently version 1.17.0 is available as well

```log
15:29:44[Geometry][error]-models/entity/test_1.18.0.geo.json | Error: geometry file format version: 1.18.0 exceeds game version: 1.17.0.  Skipping.
```

**Comment by DaanV2** [comment]
Im not getting an error on model files with 1.16.0

**Comment by JannisX11** [comment]
Oh nevermind, I had enother JSON schema that was conflicting.

**Comment by DaanV2** [comment]
No worries 😄
