### ISSUE TITLE
on_equip/on_unequip

### ISSUE THREAD

**Issue by DinnerBeef** [Blockception/Minecraft-bedrock-json-schemas#6]
**Describe the bug**
When using on_equip/on_unequip in your entity json file in BP it saying it need to be a string but it can be other things as seen here. 
https://docs.microsoft.com/en-us/minecraft/creator/reference/content/entityreference/examples/entitycomponents/minecraftcomponent_equippable

look at the horse example

Version: 2.1.57

**Comment by DaanV2** [comment]
Apparently, it does work like if you set the format_version to 1.16.0.

Do you have working examples of lower format_versions?

**Comment by DaanV2** [comment]
works on all format_versions
