### ISSUE TITLE
Check spawn rules filter: minecraft:operator

### ISSUE THREAD

**Issue by DaanV2** [Blockception/Minecraft-bedrock-json-schemas#78]
Check if the spawn rule filter: minecraft:operator is update to date

**Comment by stirante** [comment]
I believe this was mistakenly added under spawn rules on official docs.
https://learn.microsoft.com/en-us/minecraft/creator/reference/content/entityreference/examples/definitions/nestedtables/operator

**Comment by DaanV2** [comment]
Whoops :D
